# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "discreet_proxy"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Julik Tarkhanov"]
  s.date = "2011-12-10"
  s.email = "me@julik.nl"
  s.executables = ["flame_proxy_icon"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "bin/flame_proxy_icon",
    "lib/discreet_proxy.rb",
    "test/converted_png_proxies/Kanaty.stabilizer.p.p.png",
    "test/converted_png_proxies/Medianize.stabilizer.p.p.png",
    "test/converted_png_proxies/Portretten_Erasmusbrug_Pts.stabilizer.p.p.png",
    "test/converted_png_proxies/Ripples.glsl.p.p.png",
    "test/converted_png_proxies/Tezt_flame_5_trackers.stabilizer.p.p.png",
    "test/converted_png_proxies/doberman.batch.p.p.png",
    "test/converted_png_proxies/e292_v02.batch.p.p.png",
    "test/converted_png_proxies/e292_v02shadow.batch.p.p.png",
    "test/converted_png_proxies/spontaan.stabilizer.p.p.png",
    "test/converted_png_proxies/spontaan2.stabilizer.p.p.png",
    "test/converted_png_proxies/t2.batch.p.p.png",
    "test/helper.rb",
    "test/test_discreet_proxy.rb",
    "test/test_proxies/Kanaty.stabilizer.p",
    "test/test_proxies/Medianize.stabilizer.p",
    "test/test_proxies/Portretten_Erasmusbrug_Pts.stabilizer.p",
    "test/test_proxies/Ripples.glsl.p",
    "test/test_proxies/Tezt_flame_5_trackers.stabilizer.p",
    "test/test_proxies/doberman.batch.p",
    "test/test_proxies/e292_v02.batch.p",
    "test/test_proxies/e292_v02shadow.batch.p",
    "test/test_proxies/spontaan.stabilizer.p",
    "test/test_proxies/spontaan2.stabilizer.p",
    "test/test_proxies/t2.batch.p"
  ]
  s.homepage = "http://github.com/julik/discreet_proxy"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "Parses and creates Flame/Smoke .p proxy icon files"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<chunky_png>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
    else
      s.add_dependency(%q<chunky_png>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    end
  else
    s.add_dependency(%q<chunky_png>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
  end
end

